In [1]:
import numpy as np

In [9]:
file = np.genfromtxt("iris.csv", dtype = 'float', delimiter = ',', skip_header = 1, usecols =(0,1,2,3))
print(file.shape)
#print(file)

(150, 4)


In [10]:
print(file[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [14]:
print(file[0,0])
print(file[0][0])

5.1
5.1


In [16]:
#retrive first column
print(file[:,0])

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]


In [22]:
#retrieve last 2 cells of last row and last 2 cells of second to last row
print(file[148:,2:])
print(file[-2:,-2:])

[[5.4 2.3]
 [5.1 1.8]]
[[5.4 2.3]
 [5.1 1.8]]


In [24]:
#retrieve all values greater than 4
print(file[file>4])

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 4.4 5.4
 5.1 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 4.1 5.5
 4.2 4.9 5.  5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.
 4.7 6.4 4.5 6.9 4.9 5.5 6.5 4.6 5.7 4.5 6.3 4.7 4.9 6.6 4.6 5.2 5.  5.9
 4.2 6.  6.1 4.7 5.6 6.7 4.4 5.6 4.5 5.8 4.1 6.2 4.5 5.6 5.9 4.8 6.1 6.3
 4.9 6.1 4.7 6.4 4.3 6.6 4.4 6.8 4.8 6.7 5.  6.  4.5 5.7 5.5 5.5 5.8 6.
 5.1 5.4 4.5 6.  4.5 6.7 4.7 6.3 4.4 5.6 4.1 5.5 5.5 4.4 6.1 4.6 5.8 5.
 5.6 4.2 5.7 4.2 5.7 4.2 6.2 4.3 5.1 5.7 4.1 6.3 6.  5.8 5.1 7.1 5.9 6.3
 5.6 6.5 5.8 7.6 6.6 4.9 4.5 7.3 6.3 6.7 5.8 7.2 6.1 6.5 5.1 6.4 5.3 6.8
 5.5 5.7 5.  5.8 5.1 6.4 5.3 6.5 5.5 7.7 6.7 7.7 6.9 6.  5.  6.9 5.7 5.6
 4.9 7.7 6.7 6.3 4.9 6.7 5.7 7.2 6.  6.2 4.8 6.1 4.9 6.4 5.6 7.2 5.8 7.4
 6.1 7.9 6.4 6.4 5.6 6.3 5.1 6.1 5.6 7.7 6.1 6.3 5.6 6.4 5.5 6.  4.8 6.9
 5.4 6.7 5.6 6.9 5.1 5.8 5.1 6.8 5.9 6.7 5.7 6.7 5.2 6.3 5.  6.5 5.2 6.2
 5.4 5.9 5.1]


In [32]:
#retrieve all rows that have at least one value of five
five = file > 5
rowsum = np.sum(five, axis = 1)

print(file[rowsum > 0,:].shape)
print(file[rowsum > 0,:])


(118, 4)
[[5.1 3.5 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [5.4 3.7 1.5 0.2]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [5.1 3.3 1.7 0.5]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [5.5 3.5 1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.1 3.8 1.9 0.4]
 [5.1 3.8 1.6 0.2]
 [5.3 3.7 1.5 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5

In [35]:
#calculate mean median stddev of first column
print(np.mean(file[:,0]))

5.843333333333334


In [36]:
#calculate correlation coefficcient between 1st and 4th colum
#help(corrcoef)
print(np.corrcoef(file[:,0], file[:,3]))

[[1.         0.81795363]
 [0.81795363 1.        ]]


In [37]:
#resize add 5 rows
np.resize(file, (155,4)).shape

(155, 4)

In [46]:
#append add five new rows of random numbers between 30 and 40
rdm = np.random.randint(30, 40, (5, 4))
print(rdm)
x = np.append(file, rdm, axis = 0)
print(x)


[[30 35 39 33]
 [35 35 39 32]
 [30 32 34 39]
 [36 38 30 34]
 [30 32 31 33]]
[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5

In [47]:
#fill last 5 rows with random number between 10 and 20
for i in range(150, 155):
    x[i,] = np.random.rand(4)*10 +10
print(x[-5:,])

[[17.43399543 14.75312422 13.64458679 19.50385738]
 [14.12911061 10.77730295 19.67550122 16.93566449]
 [15.17502241 18.03191697 15.70435546 15.92587499]
 [10.84810658 10.58454313 18.34256794 17.230043  ]
 [10.2451622  13.90624309 15.19313132 11.70331307]]
