In [1]:
import numpy as np

In [31]:
#task 2
one = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
two = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
three = np.array([[[1],[2]],[[3],[4]]])
print("one",one)
print("two",two)
print("three",three)

print("...one element")
print("one[0,1,2] = ",one[0,1,2])
print("two[0,1,1] = ",two[0,1,1])
print("three[0,0,0] = ",three[0,0,0])

print("...one dimension")
print("one[1:] is ",one[1:])
print("two[1:] is ",two[1:])
print("three[1:] is",three[1:])

print("...subset of one dimension")
print("one[0,1:]")
print(one[0,1:])
print("two[0,1:]")
print(two[0,1:])
print("three[1,1:]")
print(three[1,1:])

one [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
two [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
three [[[1]
  [2]]

 [[3]
  [4]]]
...one element
one[0,1,2] =  6
two[0,1,1] =  4
three[0,0,0] =  1
...one dimension
one[1:] is  [[[ 7  8  9]
  [10 11 12]]]
two[1:] is  [[[ 7  8]
  [ 9 10]
  [11 12]]]
three[1:] is [[[3]
  [4]]]
...subset of one dimension
one[0,1:]
[[4 5 6]]
two[0,1:]
[[3 4]
 [5 6]]
three[1,1:]
[[4]]


In [27]:
print(one[0:])
print("next")
print(one[0,])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
next
[[1 2 3]
 [4 5 6]]


In [68]:
#task3
four = np.random.random((3,3))
print(four)
print("four < .4")
print(four < .4)
a = four < .4
print("four > .6")
print(four > .6)
b = four > .6
print(b)
print("four = .5")
print(four == .5)
print("four < .4 or four > .6")
print(np.logical_or(a, b))
print("four < .4 and four > .6")
print(np.logical_and(a, b))

[[0.31086027 0.38707536 0.49853158]
 [0.30146559 0.1656742  0.19125123]
 [0.59409679 0.20712214 0.51587035]]
four < .4
[[ True  True False]
 [ True  True  True]
 [False  True False]]
four > .6
[[False False False]
 [False False False]
 [False False False]]
[[False False False]
 [False False False]
 [False False False]]
four = .5
[[False False False]
 [False False False]
 [False False False]]
four < .4 or four > .6
[[ True  True False]
 [ True  True  True]
 [False  True False]]
four < .4 and four > .6
[[False False False]
 [False False False]
 [False False False]]


In [71]:
#task4
help(np.resize)

Help on function resize in module numpy:

resize(a, new_shape)
    Return a new array with the specified shape.
    
    If the new array is larger than the original array, then the new
    array is filled with repeated copies of `a`.  Note that this behavior
    is different from a.resize(new_shape) which fills with zeros instead
    of repeated copies of `a`.
    
    Parameters
    ----------
    a : array_like
        Array to be resized.
    
    new_shape : int or tuple of int
        Shape of resized array.
    
    Returns
    -------
    reshaped_array : ndarray
        The new array is formed from the data in the old array, repeated
        if necessary to fill out the required number of elements.  The
        data are repeated in the order that they are stored in memory.
    
    See Also
    --------
    ndarray.resize : resize an array in-place.
    
    Notes
    -----
    i.e. it does not apply interpolation/extrapolation.
    It fills the return array with the required 

In [72]:
help(np.transpose)

Help on function transpose in module numpy:

transpose(a, axes=None)
    Permute the dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : list of ints, optional
        By default, reverse the dimensions, otherwise permute the axes
        according to the values given.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    moveaxis
    argsort
    
    Notes
    -----
    Use `transpose(a, argsort(axes))` to invert the transposition of tensors
    when using the `axes` keyword argument.
    
    Transposing a 1-D array returns an unchanged view of the original array.
    
    Examples
    --------
    >>> x = np.arange(4).reshape((2,2))
    >>> x
    array([[0, 1],
           [2, 3]])
    
    >>> np.transpose(x)
    array([[0, 2],
           [1, 3]])
    
    >>> x = np.ones((1, 2, 3))
    >>> np.transpose(x, (1, 0, 2)).s

In [77]:
#task5
five = np.array([[1,2,3],[4,5,6]])
print("matrix")
print(five)
print("transpose")
print(np.transpose(five))
print("again")
print(five.T)

matrix
[[1 2 3]
 [4 5 6]]
transpose
[[1 4]
 [2 5]
 [3 6]]
again
[[1 4]
 [2 5]
 [3 6]]


In [82]:
print("resize 2 extra col")
print(np.resize(five,(2,5)))
print("resize 1 extra row")
print(np.resize(five, (3,3)))

resize 2 extra col
[[1 2 3 4 5]
 [6 1 2 3 4]]
resize 1 extra row
[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [84]:
six = np.random.random((8,2))
print(six)
print("resize")
print(np.resize(six, (4,4)))

[[0.23891594 0.63432323]
 [0.9415917  0.44887263]
 [0.0823098  0.05059502]
 [0.96818217 0.96240101]
 [0.29773921 0.99846199]
 [0.7609956  0.47429737]
 [0.21389678 0.60515275]
 [0.94271506 0.56170953]]
resize
[[0.23891594 0.63432323 0.9415917  0.44887263]
 [0.0823098  0.05059502 0.96818217 0.96240101]
 [0.29773921 0.99846199 0.7609956  0.47429737]
 [0.21389678 0.60515275 0.94271506 0.56170953]]


In [134]:
seven = np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]]])
print(seven)
print("append row")
print(np.append(seven, [[[1,1,1]],[[2,2,2]]], axis =1))

print("append col")
print(np.append(seven, [[[1],[1]],[[2],[2]]], axis = 2))

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [4 5 6]]]
append row
[[[1 2 3]
  [2 3 4]
  [1 1 1]]

 [[3 4 5]
  [4 5 6]
  [2 2 2]]]
append col
[[[1 2 3 1]
  [2 3 4 1]]

 [[3 4 5 2]
  [4 5 6 2]]]


In [165]:
eight = np.array([[1,10,100],[2,20,200],[3,30,300]])
print(eight)
print("add column of 6's")
print(np.insert(eight, 0, 6, axis = 1))
print("add row of 6's")
print(np.insert(eight, 1, 6, axis = 0))
print("delete 2nd row")
print(np.delete(eight, 1, 0))
print("delete 2nd column")
print(np.delete(eight, 1, 1))


[[  1  10 100]
 [  2  20 200]
 [  3  30 300]]
add column of 6's
[[  6   1  10 100]
 [  6   2  20 200]
 [  6   3  30 300]]
add row of 6's
[[  1  10 100]
 [  6   6   6]
 [  2  20 200]
 [  3  30 300]]
delete 2nd row
[[  1  10 100]
 [  3  30 300]]
delete 2nd column
[[  1 100]
 [  2 200]
 [  3 300]]


In [168]:
# Concatentate `my_array` and `x`: similar to np.append()
my_array = np.array([1,2,3,4])
x = np.array([1,1,1,1])
print("concatenate:")
print(np.concatenate((my_array, x)))

print("adds one array another, adding colums")

# Stack arrays row-wise
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("\nvstack:")
print(np.vstack((my_array, my_2d_array)))

print("adds one array to another, adding rows")

# Stack arrays horizontally
print("\nhstack:")
print(np.hstack((my_2d_array, my_2d_array)))

print("adds two array, adding columns")

# Stack arrays column-wise
print("\ncolumn_stack:")
print(np.column_stack((my_2d_array, my_2d_array)))

print("not sure what the difference is in hstack and column_stack")

concatenate:
[1 2 3 4 1 1 1 1]
adds one array another, adding colums

vstack:
[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]
adds one array to another, adding rows

hstack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]
adds two array, adding columns

column_stack:
[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]
not sure what the difference is in hstack and column_stack


In [170]:
# Create a 2D array.
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]])
print("original:")
print(my_2d_array)

# Split `my_stacked_array` horizontally at the 2nd index
print("\nhsplit:")
print(np.hsplit(my_2d_array, 2))

print("splits array by columns into given number of arrays")

# Split `my_stacked_array` vertically at the 2nd index
print("\nvsplit:")
print(np.vsplit(my_2d_array, 2))

print("splits array by rows into given number of arrays")

original:
[[1 2 3 4]
 [5 6 7 8]]

hsplit:
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
splits array by columns into given number of arrays

vsplit:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
splits array by rows into given number of arrays
